### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by funkyluv1** [funkyluv1/UNO#62]
1. - [ ] Figure out a way to change the View with a successful example (Finish by Today)
2. Usecase (Finish by Thursday)

- [ ] Siwei: Confirm usecase
- [ ] Daniel: Left/Right shift usecase
- [ ] Aaron: Next usecase
- [ ] Cynthia: Round usecase
- [ ] Tony: push Select/ Undo usecase
- [ ] David: GetCard usecase

3. - [ ] Testing and Debugging (Finish by Friday)
4. - [ ] Slide and presentation script (Finish by weekends)
